entryPoints:
  http:
    address: ":80"
  dashboard:
    address: ":8000"

providers:
  docker:
    network: bpi-traefik
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

api:
  insecure: true
  dashboard: true